
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { ChartBar, ChartLine } from "lucide-react";
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent
} from "@/components/ui/chart";
import { 
  LineChart, 
  Line, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  ResponsiveContainer,
  AreaChart,
  Area,
  PieChart,
  Pie,
  Cell,
  Tooltip
} from "recharts";

const WEEKLY_DATA = [
  { day: 'Mon', congestion: 65, emissions: 80, accidents: 2 },
  { day: 'Tue', congestion: 59, emissions: 75, accidents: 1 },
  { day: 'Wed', congestion: 80, emissions: 90, accidents: 3 },
  { day: 'Thu', congestion: 81, emissions: 85, accidents: 2 },
  { day: 'Fri', congestion: 56, emissions: 65, accidents: 1 },
  { day: 'Sat', congestion: 55, emissions: 60, accidents: 0 },
  { day: 'Sun', congestion: 40, emissions: 50, accidents: 0 },
];

const CONGESTION_DATA = [
  { name: 'Morning Peak', value: 35 },
  { name: 'Midday', value: 20 },
  { name: 'Evening Peak', value: 30 },
  { name: 'Night', value: 15 },
];

const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042'];

const AiInsights = () => {
  return (
    <div className="space-y-6 mt-6">
      <Card>
        <CardHeader>
          <CardTitle>AI System Performance</CardTitle>
          <CardDescription>Analysis and insights generated by the AI traffic management system</CardDescription>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="weekly">
            <TabsList className="mb-4">
              <TabsTrigger value="weekly">Weekly Analysis</TabsTrigger>
              <TabsTrigger value="monthly">Monthly Trends</TabsTrigger>
              <TabsTrigger value="predictions">Traffic Predictions</TabsTrigger>
            </TabsList>
            <TabsContent value="weekly" className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <h3 className="text-sm font-medium mb-2">Traffic Metrics Over Time</h3>
                  <div className="h-72 bg-slate-50 rounded-lg p-4">
                    <ChartContainer config={{
                      congestion: { color: "#EF4444" },
                      emissions: { color: "#3E92CC" }
                    }}>
                      <ResponsiveContainer width="100%" height="100%">
                        <LineChart data={WEEKLY_DATA}>
                          <CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" />
                          <XAxis dataKey="day" axisLine={false} tickLine={false} />
                          <YAxis 
                            axisLine={false}
                            tickLine={false}
                            width={30}
                          />
                          <ChartTooltip content={<ChartTooltipContent />} />
                          <Line 
                            type="monotone" 
                            dataKey="congestion" 
                            name="congestion"
                            stroke="#EF4444" 
                            strokeWidth={2} 
                            dot={{ r: 4 }}
                            activeDot={{ r: 6 }}
                          />
                          <Line 
                            type="monotone" 
                            dataKey="emissions" 
                            name="emissions"
                            stroke="#3E92CC" 
                            strokeWidth={2} 
                            dot={{ r: 4 }}
                            activeDot={{ r: 6 }}
                          />
                        </LineChart>
                      </ResponsiveContainer>
                    </ChartContainer>
                  </div>
                </div>
                
                <div>
                  <h3 className="text-sm font-medium mb-2">Congestion Distribution</h3>
                  <div className="h-72 bg-slate-50 rounded-lg p-4">
                    <ResponsiveContainer width="100%" height="100%">
                      <PieChart>
                        <Pie
                          data={CONGESTION_DATA}
                          cx="50%"
                          cy="50%"
                          labelLine={false}
                          outerRadius={80}
                          innerRadius={40}
                          fill="#8884d8"
                          dataKey="value"
                          label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                        >
                          {CONGESTION_DATA.map((entry, index) => (
                            <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                          ))}
                        </Pie>
                        <Tooltip />
                      </PieChart>
                    </ResponsiveContainer>
                  </div>
                </div>
              </div>
              
              <Card className="bg-smartcity-blue/5 border-smartcity-blue/20">
                <CardContent className="p-4">
                  <h3 className="font-medium mb-2 flex items-center">
                    <ChartLine className="h-4 w-4 mr-2" />
                    AI-Generated Insights
                  </h3>
                  <ul className="space-y-2 text-sm">
                    <li className="flex items-center gap-2">
                      <span className="h-2 w-2 rounded-full bg-green-500"></span>
                      Traffic flow improved by 22% during peak hours this week
                    </li>
                    <li className="flex items-center gap-2">
                      <span className="h-2 w-2 rounded-full bg-yellow-500"></span>
                      Potential bottleneck detected at Highland Ave & Oak St during 4-6 PM
                    </li>
                    <li className="flex items-center gap-2">
                      <span className="h-2 w-2 rounded-full bg-blue-500"></span>
                      Signal timing optimization reduced average wait times by 35%
                    </li>
                    <li className="flex items-center gap-2">
                      <span className="h-2 w-2 rounded-full bg-red-500"></span>
                      Recommend infrastructure review at Central Ave & Park Rd intersection
                    </li>
                  </ul>
                </CardContent>
              </Card>
            </TabsContent>
            
            <TabsContent value="monthly" className="p-4 bg-slate-50 rounded-lg text-center">
              <p>Monthly trend analysis will be available in the next update</p>
            </TabsContent>
            
            <TabsContent value="predictions" className="p-4 bg-slate-50 rounded-lg text-center">
              <p>AI traffic predictions will be available in the next update</p>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  );
};

export default AiInsights;
